# Generated by Django 4.2.6 on 2023-10-17 10:44

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_detailed_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="has_video_intro",
        ),
        migrations.AddField(
            model_name="course",
            name="video_intro",
            field=models.FileField(
                blank=True,
                help_text="Upload a video intro for the course. (e.g., MP4, AVI, MOV)",
                null=True,
                upload_to=course.models.upload_to_course_video,
            ),
        ),
    ]
