# Generated by Django 4.2.6 on 2023-10-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_module_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="slug",
        ),
    ]
