# Generated by Django 4.2.6 on 2023-10-17 12:30

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0006_lesson_created_at_lesson_instructor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.RemoveField(
            model_name="course",
            name="targeted_audience",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="order",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="module",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="module",
            name="order",
        ),
        migrations.RemoveField(
            model_name="module",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="course",
            name="detailed_description",
            field=models.TextField(help_text="Enter a detailed course description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="excerpt",
            field=models.TextField(help_text="Enter a short course description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="image_thumbnail",
            field=models.ImageField(
                help_text="Upload an image thumbnail for the course",
                upload_to="course_thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_certified",
            field=models.BooleanField(
                default=False, help_text="Check if the course is certified"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(
                default=False, help_text="Check if the course is free"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Check if the course is public"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("it", "Italian"),
                ],
                help_text="Select the course language",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the price of the course",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="requirements",
            field=models.TextField(help_text="Enter course requirements"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Enter the title of the course", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="video_intro",
            field=models.FileField(
                blank=True,
                help_text="Upload a video intro (e.g., MP4, AVI, MOV)",
                null=True,
                upload_to=course.models.upload_to_course_video,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="what_youll_learn",
            field=models.TextField(help_text="Enter what students will learn"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=course.models.upload_to_course_video
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
