# Generated by Django 4.2.6 on 2023-10-18 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "course",
            "0007_alter_course_options_remove_course_targeted_audience_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="detailed_description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="excerpt",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="requirements",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="what_youll_learn",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
