# Generated by Django 4.2.6 on 2023-10-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_alter_course_is_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_certified",
            field=models.BooleanField(help_text="Check if the course is certified"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(
                blank=True, help_text="Check if the course is free", null=True
            ),
        ),
    ]
