# Generated by Django 4.2.6 on 2023-10-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_alter_course_is_certified_alter_course_is_free"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_free",
        ),
    ]
