# Generated by Django 4.2.6 on 2023-10-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_remove_course_is_free"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the quiz", max_length=255
                    ),
                ),
                ("description", models.TextField()),
                (
                    "number_of_questions",
                    models.PositiveIntegerField(
                        help_text="Enter the number of questions in the quiz"
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        help_text="Enter the time limit for the quiz in minutes"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Check if the quiz is published"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="course.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="Enter the question text"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="course.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_text",
                    models.CharField(help_text="Enter the choice text", max_length=255),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Check if this choice is correct"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="course.question",
                    ),
                ),
            ],
        ),
    ]
