# Generated by Django 4.2.6 on 2023-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_quiz_question_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="is_published",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
