# Generated by Django 4.2.6 on 2023-10-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_quiz_course_alter_quiz_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="is_published",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
