# Generated by Django 4.2.6 on 2023-10-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0019_quiz_instructor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="instructor",
        ),
    ]
