# Generated by Django 4.2.6 on 2023-10-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_remove_quiz_course_remove_quiz_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes_course",
                to="course.course",
            ),
            preserve_default=False,
        ),
    ]
