# Generated by Django 4.2.6 on 2023-10-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0021_quiz_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
    ]
